spring:
  application:
    name: sample
  threads:
    virtual:
      enabled: true
  cache:
    cache-names: "ratingCache"

server:
  port: 8443
  servlet:
    context-path: /sample
  ssl:
    key-store: classpath:keystore/mykeystore.p12
    #key-store: ./sample-configuration/keystore/mykeystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: mysslkey
    key-password: changeit

custom:
  http-client:
    timeouts:
      default:
        connect-timeout: 3000       # in milliseconds
        read-timeout: 5000          # in milliseconds
      todos:
        connect-timeout: 3000
        read-timeout: 6000
      posts:
        connect-timeout: 3000
        read-timeout: 8000
      ratings:
        connect-timeout: 3000
        read-timeout: 15000

backends:
  crisil-ranking:
    host: intelligence.crisil.com
    uri: /content/intelligence/en/homepage/what-we-do/research/investment-research-product/mutual-fund-research/mutual-fund-ranking/_jcr_content/content_par/columncontrol_128464/col-100-1-wp/box/col-100-1/tabs_copy/1/mf_rating.mfRating.json